//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aeolus.Overzichten.Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SyncfusionBlazorLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncfusionBlazorLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aeolus.Overzichten.Blazor.Resources.SyncfusionBlazorLocale", typeof(SyncfusionBlazorLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Calendar_Today {
            get {
                return ResourceManager.GetString("Calendar-Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sfasdf.
        /// </summary>
        public static string Datepicker_placeholder {
            get {
                return ResourceManager.GetString("Datepicker-placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Grid_Add {
            get {
                return ResourceManager.GetString("Grid_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Record.
        /// </summary>
        public static string Grid_AddFormTitle {
            get {
                return ResourceManager.GetString("Grid_AddFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string Grid_AND {
            get {
                return ResourceManager.GetString("Grid_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit this column.
        /// </summary>
        public static string Grid_autoFit {
            get {
                return ResourceManager.GetString("Grid_autoFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit all columns.
        /// </summary>
        public static string Grid_autoFitAll {
            get {
                return ResourceManager.GetString("Grid_autoFitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save changes?.
        /// </summary>
        public static string Grid_BatchSaveConfirm {
            get {
                return ResourceManager.GetString("Grid_BatchSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes will be lost. Are you sure you want to continue?.
        /// </summary>
        public static string Grid_BatchSaveLostChanges {
            get {
                return ResourceManager.GetString("Grid_BatchSaveLostChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        public static string Grid_Between {
            get {
                return ResourceManager.GetString("Grid_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanks.
        /// </summary>
        public static string Grid_Blanks {
            get {
                return ResourceManager.GetString("Grid_Blanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Grid_CancelButton {
            get {
                return ResourceManager.GetString("Grid_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Cancel the changes?.
        /// </summary>
        public static string Grid_CancelEdit {
            get {
                return ResourceManager.GetString("Grid_CancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Column.
        /// </summary>
        public static string Grid_ChooseColumns {
            get {
                return ResourceManager.GetString("Grid_ChooseColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Date.
        /// </summary>
        public static string Grid_ChooseDate {
            get {
                return ResourceManager.GetString("Grid_ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Grid_ClearButton {
            get {
                return ResourceManager.GetString("Grid_ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string Grid_ClearFilter {
            get {
                return ResourceManager.GetString("Grid_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Grid_Columnchooser {
            get {
                return ResourceManager.GetString("Grid_Columnchooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column chooser dialog.
        /// </summary>
        public static string Grid_ColumnChooserDialogARIA {
            get {
                return ResourceManager.GetString("Grid_ColumnChooserDialogARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column menu dialog.
        /// </summary>
        public static string Grid_ColumnMenuDialogARIA {
            get {
                return ResourceManager.GetString("Grid_ColumnMenuDialogARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Delete Record?.
        /// </summary>
        public static string Grid_ConfirmDelete {
            get {
                return ResourceManager.GetString("Grid_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Grid_Contains {
            get {
                return ResourceManager.GetString("Grid_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Grid_Copy {
            get {
                return ResourceManager.GetString("Grid_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Export.
        /// </summary>
        public static string Grid_Csvexport {
            get {
                return ResourceManager.GetString("Grid_Csvexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Filter.
        /// </summary>
        public static string Grid_CustomFilter {
            get {
                return ResourceManager.GetString("Grid_CustomFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date.
        /// </summary>
        public static string Grid_CustomFilterDatePlaceHolder {
            get {
                return ResourceManager.GetString("Grid_CustomFilterDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer filter dialog.
        /// </summary>
        public static string Grid_CustomFilterDialogARIA {
            get {
                return ResourceManager.GetString("Grid_CustomFilterDialogARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the value.
        /// </summary>
        public static string Grid_CustomFilterPlaceHolder {
            get {
                return ResourceManager.GetString("Grid_CustomFilterPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Filters.
        /// </summary>
        public static string Grid_DateFilter {
            get {
                return ResourceManager.GetString("Grid_DateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime Filters.
        /// </summary>
        public static string Grid_DateTimeFilter {
            get {
                return ResourceManager.GetString("Grid_DateTimeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records selected for delete operation.
        /// </summary>
        public static string Grid_DeleteOperationAlert {
            get {
                return ResourceManager.GetString("Grid_DeleteOperationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        public static string Grid_DeleteRecord {
            get {
                return ResourceManager.GetString("Grid_DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit dialog.
        /// </summary>
        public static string Grid_DialogEditARIA {
            get {
                return ResourceManager.GetString("Grid_DialogEditARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of .
        /// </summary>
        public static string Grid_EditFormTitle {
            get {
                return ResourceManager.GetString("Grid_EditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records selected for edit operation.
        /// </summary>
        public static string Grid_EditOperationAlert {
            get {
                return ResourceManager.GetString("Grid_EditOperationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        public static string Grid_EditRecord {
            get {
                return ResourceManager.GetString("Grid_EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource must not be empty at initial load since columns are generated from dataSource in AutoGenerate Column Grid.
        /// </summary>
        public static string Grid_EmptyDataSourceError {
            get {
                return ResourceManager.GetString("Grid_EmptyDataSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display.
        /// </summary>
        public static string Grid_EmptyRecord {
            get {
                return ResourceManager.GetString("Grid_EmptyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With.
        /// </summary>
        public static string Grid_EndsWith {
            get {
                return ResourceManager.GetString("Grid_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the value.
        /// </summary>
        public static string Grid_EnterValue {
            get {
                return ResourceManager.GetString("Grid_EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        public static string Grid_Equal {
            get {
                return ResourceManager.GetString("Grid_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export.
        /// </summary>
        public static string Grid_Excelexport {
            get {
                return ResourceManager.GetString("Grid_Excelexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel filter dialog.
        /// </summary>
        public static string Grid_ExcelFilterDialogARIA {
            get {
                return ResourceManager.GetString("Grid_ExcelFilterDialogARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Grid_Export {
            get {
                return ResourceManager.GetString("Grid_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string Grid_False {
            get {
                return ResourceManager.GetString("Grid_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&apos;s filter bar cell.
        /// </summary>
        public static string Grid_FilterbarTitle {
            get {
                return ResourceManager.GetString("Grid_FilterbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Grid_FilterButton {
            get {
                return ResourceManager.GetString("Grid_FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string Grid_FilterFalse {
            get {
                return ResourceManager.GetString("Grid_FilterFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Grid_FilterMenu {
            get {
                return ResourceManager.GetString("Grid_FilterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter menu dialog.
        /// </summary>
        public static string Grid_FilterMenuDialogARIA {
            get {
                return ResourceManager.GetString("Grid_FilterMenuDialogARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string Grid_FilterTrue {
            get {
                return ResourceManager.GetString("Grid_FilterTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string Grid_FirstPage {
            get {
                return ResourceManager.GetString("Grid_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        public static string Grid_GreaterThan {
            get {
                return ResourceManager.GetString("Grid_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than Or Equal.
        /// </summary>
        public static string Grid_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Grid_GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by this column.
        /// </summary>
        public static string Grid_Group {
            get {
                return ResourceManager.GetString("Grid_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping is disabled for this column.
        /// </summary>
        public static string Grid_GroupDisable {
            get {
                return ResourceManager.GetString("Grid_GroupDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Drag a column header here to group its column.
        /// </summary>
        public static string Grid_GroupDropArea {
            get {
                return ResourceManager.GetString("Grid_GroupDropArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Filter Data.
        /// </summary>
        public static string Grid_InvalidFilterMessage {
            get {
                return ResourceManager.GetString("Grid_InvalidFilterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string Grid_Item {
            get {
                return ResourceManager.GetString("Grid_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string Grid_Items {
            get {
                return ResourceManager.GetString("Grid_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string Grid_LastPage {
            get {
                return ResourceManager.GetString("Grid_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        public static string Grid_LessThan {
            get {
                return ResourceManager.GetString("Grid_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than Or Equal.
        /// </summary>
        public static string Grid_LessThanOrEqual {
            get {
                return ResourceManager.GetString("Grid_LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string Grid_MatchCase {
            get {
                return ResourceManager.GetString("Grid_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches Found.
        /// </summary>
        public static string Grid_Matchs {
            get {
                return ResourceManager.GetString("Grid_Matchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string Grid_NextPage {
            get {
                return ResourceManager.GetString("Grid_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches Found.
        /// </summary>
        public static string Grid_NoResult {
            get {
                return ResourceManager.GetString("Grid_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Equal.
        /// </summary>
        public static string Grid_NotEqual {
            get {
                return ResourceManager.GetString("Grid_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Filters.
        /// </summary>
        public static string Grid_NumberFilter {
            get {
                return ResourceManager.GetString("Grid_NumberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Grid_OKButton {
            get {
                return ResourceManager.GetString("Grid_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Grid_OR {
            get {
                return ResourceManager.GetString("Grid_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Export.
        /// </summary>
        public static string Grid_Pdfexport {
            get {
                return ResourceManager.GetString("Grid_Pdfexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string Grid_PreviousPage {
            get {
                return ResourceManager.GetString("Grid_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Grid_Print {
            get {
                return ResourceManager.GetString("Grid_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Grid_Save {
            get {
                return ResourceManager.GetString("Grid_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Grid_SaveButton {
            get {
                return ResourceManager.GetString("Grid_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Grid_Search {
            get {
                return ResourceManager.GetString("Grid_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search columns.
        /// </summary>
        public static string Grid_SearchColumns {
            get {
                return ResourceManager.GetString("Grid_SearchColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Grid_SelectAll {
            get {
                return ResourceManager.GetString("Grid_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rows where:.
        /// </summary>
        public static string Grid_ShowRowsWhere {
            get {
                return ResourceManager.GetString("Grid_ShowRowsWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With.
        /// </summary>
        public static string Grid_StartsWith {
            get {
                return ResourceManager.GetString("Grid_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Filters.
        /// </summary>
        public static string Grid_TextFilter {
            get {
                return ResourceManager.GetString("Grid_TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string Grid_True {
            get {
                return ResourceManager.GetString("Grid_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to ungroup.
        /// </summary>
        public static string Grid_UnGroup {
            get {
                return ResourceManager.GetString("Grid_UnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup by this column.
        /// </summary>
        public static string Grid_Ungrouping {
            get {
                return ResourceManager.GetString("Grid_Ungrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Export.
        /// </summary>
        public static string Grid_Wordexport {
            get {
                return ResourceManager.GetString("Grid_Wordexport", resourceCulture);
            }
        }
    }
}
